image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -version
          - mvn -f ./basicmachine/pom.xml -B verify
