image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -version
          - mvn -f https://bitbucket.org/larsatzinger/vro-plugin-basicmachine/src/master/basicmachine/pom.xml -B verify
